### ISSUE TITLE
Compared with P3D

### ISSUE THREAD

**Issue by leesky1c** [yoosan/i3d-tensorflow#5]
Hello, yoosan,

I am new to do research on video understanding. I want to compare the performance of these two network, both P3D and I3D based on ResNet, and which one is better? Their architectures are similar. 

Did you have any understanding about them?

Thx!

**Comment by yoosan** [comment]
Sorry leeskyed,
  We have not done such experiments. According to the paper, p3d should outperform i3d.

**Comment by leesky1c** [comment]
Thank your for your reply. I would close this issue.
